
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class FramePrincipal extends javax.swing.JFrame {
    static Connection con;
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnVencidos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        btnMediaFornecedor = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNProdutos = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        btnMostraCat = new javax.swing.JButton();
        btnAtt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProdutos = new javax.swing.JMenu();
        menuCadastroProdutos = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        btnSairSistema = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVencidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-expired-24.png"))); // NOI18N
        btnVencidos.setText("Produtos vencidos");
        btnVencidos.setToolTipText("Mostra os produtos vencidos");
        btnVencidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVencidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVencidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 170, -1));

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome:", "Data de vencimento:", "Preço de compra:", "Quantidade:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 120));

        btnMediaFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-estimate-24.png"))); // NOI18N
        btnMediaFornecedor.setText("Média por fornecedor");
        btnMediaFornecedor.setToolTipText("Mostra a média do preço dos produtos conforme o fornecedor escolhido");
        btnMediaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnMediaFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 170, -1));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-close-window-24.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        lblNProdutos.setText("Número de produtos: ");
        getContentPane().add(lblNProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-print-24.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 170, -1));

        btnMostraCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-category-24.png"))); // NOI18N
        btnMostraCat.setText("Ver categoria");
        btnMostraCat.setToolTipText("Mostra a categoria do produto. Ex (Fruta, Carne, Legume, etc)");
        btnMostraCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostraCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 170, -1));

        btnAtt.setText("Atualizar Tabela");
        btnAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, -1, -1));

        menuProdutos.setText("Produtos");

        menuCadastroProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuCadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-keyboard-24.png"))); // NOI18N
        menuCadastroProdutos.setText("Cadastrar produtos...");
        menuCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroProdutosActionPerformed(evt);
            }
        });
        menuProdutos.add(menuCadastroProdutos);

        jMenuBar1.add(menuProdutos);

        menuSair.setText("Sair");

        btnSairSistema.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        btnSairSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-close-window-24.png"))); // NOI18N
        btnSairSistema.setText("Sair do sistema");
        btnSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairSistemaActionPerformed(evt);
            }
        });
        menuSair.add(btnSairSistema);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairSistemaActionPerformed

    private void menuCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroProdutosActionPerformed
        DialogCadProdutos dcp = new DialogCadProdutos(this, true);
        dcp.setVisible(true);
    }//GEN-LAST:event_menuCadastroProdutosActionPerformed

    private void btnVencidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVencidosActionPerformed
        DialogVencidos dv = new DialogVencidos(this, true);
        dv.setVisible(true);
    }//GEN-LAST:event_btnVencidosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            con = DriverManager.getConnection("jdbc:sqlite:banco.db");
            mostrarDados();
            lblNProdutos.setText("Número de produtos: " + contagem());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnMediaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaFornecedorActionPerformed
        DialogMediaFornecedor dmf = new DialogMediaFornecedor(this, true);
        dmf.setVisible(true);
    }//GEN-LAST:event_btnMediaFornecedorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            tabelaDados.print();
        } catch (PrinterException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnMostraCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraCatActionPerformed
        DialogMostraCat dmc = new DialogMostraCat(this, true);
        dmc.setVisible(true);
    }//GEN-LAST:event_btnMostraCatActionPerformed

    private void btnAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttActionPerformed
        mostrarDados();
        lblNProdutos.setText("Número de produtos: " + contagem());
    }//GEN-LAST:event_btnAttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    private void mostrarDados(){
                try {
                    PreparedStatement ps = con.prepareStatement("SELECT * FROM produtos");
                    ResultSet rs = ps.executeQuery();
                    DefaultTableModel model = (DefaultTableModel) tabelaDados.getModel();
                    model.setRowCount(0);
                    
                    while (rs.next()) {
                        Object linha[] = { rs.getString("nome"), rs.getString("vencimento"), rs.getString("precocompra"), rs.getString("quantidade")
                        };
                        model.addRow(linha);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                
            }
    private int contagem(){
                    int linha = tabelaDados.getModel().getRowCount();
                    return linha;
             }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtt;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnMediaFornecedor;
    private javax.swing.JButton btnMostraCat;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem btnSairSistema;
    private javax.swing.JButton btnVencidos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNProdutos;
    private javax.swing.JMenuItem menuCadastroProdutos;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuSair;
    private javax.swing.JTable tabelaDados;
    // End of variables declaration//GEN-END:variables
}
